baseURL = 'https://Moeti-Mphoso.github.io'
languageCode = 'en-us'
title = 'Moeti Mphoso'
theme = "cactus"

[params]
    colortheme = "white"
    description = "Hi! My name is Moeti Mphoso, I'm a Data Engineer. I'm from Lesotho, living in South Africa and currently working at HISP-SA. This website provides information about me, what I am working on and thinking about, and blog posts on topics of interest to me. My writings are ongoing works, when i have a thought, I just write it down and publish it, I call this posts `Published drafts`, some of them are even just blank pages on topics I want to research and write about."
    mainSection = "posts"
    mainSectionTitle = "Blog Posts"
    showAllPostsOnHomePage = false
    postsOnHomePage = 10
    showProjectsList = false
    projectsUrl = "https://github.com/Moeti-Mphoso"


[[params.social]]
  name = "github"
  link = "https://github.com/Moeti-Mphoso"

[[params.social]]
  name = "email"
  link = "mphoso.p.m@gmail.com"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/moeti-mphoso-b8048985/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
